services:
  - type: web
    name: django-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn learning_path.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: learning_path.settings
      - key: SECRET_KEY
        value: "django-insecure-#^e05z*7otx0_&tua0m09!#&e(vw488=g_u2y6q%o=q#0ii!w#"
      - key: DEBUG
        value: "False"
